basic/code21.s, basic/code8.s
The reason for the bug was that the FIN function uses a literal value for the negative sign, $2D, see here:
https://www.pagetable.com/c64disasm/#BCFE
but the EVAL function, which is called by the FRMEVL function, uses the minus token, $AB, see here:
https://www.pagetable.com/c64disasm/#AEB1
But the values in a DATA statement are not tokenized, so it reads the literal minus, $2D, and since it doesn't recognize it, it results in a syntax error.
This fix adds the $ and % functionality with as few side effects for the existing functionality as possible, so every existing C64 program should now work. Test case (might be good to have some automatic regression testing) :
```
10 READ A, B, C, D, E$, F$, G$, H, I
20 READ J,K,L,M,N,O,P,Q
30 READ R,S,T,U,V,W,X
40 PRINT A;B;C;D;E$;F$;G$;H;I
50 PRINT …
```
=> fix for $ and % in DATA statements

charset/iso-8859-15.s
I think no characters should have identical bitmaps in 8x8, because it could lead to errors when coding or writing. There are still characters to fix, but this is a start.
=> Update iso-8859-15.s for º, Ö, ö

basic/code26.s, basic/declare.s, basic/token2.s, basic/tokens.s, basic/x16additions.s, kernal/declare.s, kernal/load.s, kernal/messages.s
_There are some issues with this PR that will probably require discussion._
This PR does a few things:
- add a `VLOAD` command to load files directly into video RAM
- extend the `LOAD` command to allow specifying a RAM bank and address
- disable the `VERIFY` command (to make room in BASIC ROM for the other changes)
The new functionality is currently incompatible with the emulator because the emulator intercepts calls to the KERNAL load subroutine for device 1.  I was able to test by temporarily modifying a few of the KERNAL IO subroutines to stream dummy data on device 8.
The `LOAD` command can now be used in either of two forms:
- `LOAD [filename[,device[,relocate]]]` (the original form)
- `LOAD [filename[,device[,bank,address]]]`
In the second form, the RAM bank is switched, then the …
=> Allow LOAD with address and add VLOAD

README.md
This also notes that a built version of `rom.bin` is included with emulator releases, and makes clear in the README that the ROM version currently must be contemporary with the emulator.
=> README: Add build and some cc65 install instructions

basic/code26.s
This fixes https://github.com/commanderx16/x16-emulator/issues/162
This fixes https://github.com/commanderx16/x16-rom/issues/47
Due to an incorrect branch, the accumulator wasn't being restored after the call to parse the LOAD parameters.  As a result, the KERNAL was loading the data into video memory instead of normal RAM.
=> Fix a bug in LOAD/VERIFY

README.md
Brief addition to README for the macOS installation. cc65 is actually provided by homebrew
=> Added instructions for macOS

.travis.yml, README.md
Similar to my [commit](https://github.com/commanderx16/x16-emulator/commit/f34190deb98ef27f9baf85e64751a36a607fbd65) on the emulator repository, this will build PRs on Travis CI to verify patches do not break the build. As before the owner of the repository needs to enable the repository on Travis CI to get the builds running. [Here](https://travis-ci.org/tobier/x16-rom/builds/595503666) is a build on my fork that runs and passes.
=> Add Travis CI integration for Linux and macOS to check PRs

kernal/load.s
This changes the LOAD command to wrap into the next RAM bank whenever it reaches the end of the high RAM area.  This makes it easy to load files larger than 8K into high memory.
Corresponding Emulator change: https://github.com/commanderx16/x16-emulator/pull/165
Credit for the idea goes to [Artur Bujdoso](https://www.facebook.com/groups/CommanderX16/permalink/517307852353647/?comment_id=517330952351337) and/or [Tom Wilson](https://www.facebook.com/groups/CommanderX16/permalink/524303641654068/?comment_id=524556388295460).
=> Make load routine wrap into next RAM bank

rom.cfg
First off, I'm still not entirely familiar with how the ROM project functionally works yet, and I might be completely wrong about this. However, from what I've figured out so far, this appears to be the right change to make. Let me know if I'm wrong about this.
I noticed what (I think) is a typo in rom.cfg. When setting the addresses for `IRQA` and `IRQB` (for `CBDOS` and `GEOS`), they were put in the wrong page. I think what happened was that they used the value from the previous memory's `size` parameter, instead of the previous memory's `start + size` value. These two appear to be the only ones that have this issue.
=> Fix address mistakes in rom.cfg

basic/init.s
This fixes issue https://github.com/commanderx16/x16-rom/issues/82.
I've tested a little. This makes the ROM longer by one byte, I presume, and that might have some side effects that I don't know about.
=> $8F (set PETSCII-UC even if ISO) printed first after reset

kernal/editor.1.s
Swaps the foreground and background colors using ctrl-b ($02). Used for setting text bg color by setting fg color, swapping, and setting new fg color. Also can be used as a single code reverse toggle.
=> Swap foreground/background PETSCII control code.

README.md
Bank 0 is used by the OS now, instead of the upper-most bank.
=> Updated bank information to reflect recent ROM

README.md
As there are architectural changes with RHEL 8 and deriveratives, they will need to perform additional steps to be able to install cc65. This has been documented properly.
=> Add additional notes for RHEL 8+ users

kernal/drivers/x16/screen.s
Preserve X register in inicpy so cpycustom starts at the right address.
=> Start at the right address when loading custom charset

cbdos/main.s
Reading files from the SD card was failing if the file length was an exact multiple of the block size of 512 bytes. It turns out CBDOS read_block was doing a less than comparison instead of a less than or equals, so if the last block completely filled the buffer, it would not flag it internally as being the last block, so it would continue trying to read new blocks from the file without sending an EOF. Added a check to set the last block flag when the remaining bytes hits zero.
=> Fix CBDOS read_block to handle last block filling buffer completely

kernal/drivers/x16/framebuffer.s
FB_set_pixels treated the restore of the registers wrong so it crashed when count is > 255. This has been corrected. Fixes #179 
Notice that FB_get_pixels already worked correctly.
=> fix crash in FB_set_pixels for count>255. Fixes #179

kernal/open-roms/iostack/f4a5.load.s
This pull request is to correct the issue discussed in [f4a5.load.s - STY vs STA](https://github.com/commanderx16/x16-rom/issues/171#issue-696453552).
=> Bug Fix: The wrong register was loaded into STAL+1

kernal/cbm/channel/load.s, kernal/ieee_switch.s
The code was saving the old SA in X, which was getting clobbered before it tried to use it to determine whether to save using the disk address or passed-in address. This changes "talk" and "listn" to preserve X on the stack so they are not lost at the upper levels.
=> [DOS] Fix loading to the passed-in address when SA is 0

inc/banks.inc, kernal/drivers/x16/joystick.s
KVARS_START_TRASH_NZ and KVARS_END_TRASH_NZ are preserving A across the entire function call, in the one place where they're used this seems to be both unnecessary and incorrect, the A only needs to be preserved across the macro, and explicitly *should not* be preserved across the whole call. This seems to fix joystick polling, verified with the following test:
10?JOY(1):GOTO10
RUN
See also issue #200
=> Fix issue #200

inc/banks.inc, kernal/drivers/x16/joystick.s
KVARS_START_TRASH_NZ and KVARS_END_TRASH_NZ are not interrupt-safe. If the macros are interrupted by an ISR that also uses the KVARS macros, kvswitch_tmp1 will likely be overwritten. This pull request modifies joystick_get to use KVARS_START and KVARS_END, which are interrupt-safe. This change fixes #203. This pull request also adds a warning about interrupt safety to inc/banks.inc.
=> Fix a race condition in joystick_get

inc/jsrfar.inc
This pull request removes a line from inc/jsrfar.inc that limits the ROM banks that can be jumped to, which fixes #205. Considering that [this video](https://www.youtube.com/watch?v=Y-c3c3ia9Bo) mentions that the other banks may be usable with a few hardware modifications, I decided to completely remove the check rather than replacing it.
=> Remove ROM banking limitations from JSRFAR

inc/jsrfar.inc
This commit fixes #209 by adding a couple instructions to avoid clobbering P when returning from JSRFAR to RAM BANK.
=> add code to preserve P register upon return from JSRFAR RAM BANK

kernal/cbm/channel/load.s
This pull request gives the kernal load routine the ability to load files that do not have a two-byte address header. This is done by interpreting the secondary address as described below:
<table>
<tr>
<th>Name</th>
<th>Bit&nbsp;7</th>
<th>Bit&nbsp;6</th>
<th>Bit&nbsp;5 </th>
<th>Bit&nbsp;4</th>
<th>Bit&nbsp;3 </th>
<th>Bit&nbsp;2</th>
<th>Bit&nbsp;1 </th>
<th>Bit&nbsp;0</th>
</tr>
<tr>
<td align="center">SA</td>
<td colspan="6" align="center">Unused</td>
<td align="center">Write Header</td>
<td align="center">Address Source</td>
</tr>
</table>
If **Address Source** is 0, the load address is taken from the X/Y registers. If **Address Source** is 1, the load address is taken from the file header. Using the first bit in this way allows for partial backwards compatibility with previous …
=> Add support for headerless files

basic/code10.s, basic/code14.s, basic/x16additions.s
Curious bug in DA$/TI$ (date + time) in X16 BASIC.
"PRINT DA$;TI$" was fine but "PRINT DA$+TI$" would get corrupted DA$.  BIN$() and HEX$() would corrupt DA$/TI$ but not be corrupted in turn.
The cause of this issue was how 'strlit' handled the input string, depending on what page it started in.  Pages 0 and 2 seem to get special treatment (I think they're copied while other pages, assumed to be BASIC program code, are not).
DA$, TI$, BIN$(), and HEX$() all use 'lofbuf' ($FF).  To skip initial matter, DA$ and TI$ pass 'lofbuf+2' and 'lofbuf+1' which are in page 1.  So later uses of 'lofbuf' could corrupt the string.
Workaround is to use DA$+"" or the like to force it to copy the string.
Attachment: [da-ti-test.txt](https://github.com/commanderx16/x16-rom/files/7112172/da-ti-test.txt) a …
=> [BASIC] Fix DA$ and TI$ when accessed together or with BIN$()/HEX$()

basic/code17.s
The 'finh' code is clobbering the C flag, which was set by 'chrget' to indicate it didn't get a digit, and used by 'fin' in parsing numbers.  That breaks the handling of end of input in GET/READ/INPUT.
This fixes problems with GET, READ, and INPUT when handling null input as a number:
- Fixes #218 in which "GET A" with empty input gets -48.
- Fixes issue in "INPUT A,B", if "B" is empty it gets a bogus number instead.
- Fixes issue in "READ A" / "DATA ," where it gets syntax error instead of 0 and 0.
With the fix, the behavior is the same as on Commodore 64 (except for "$" and "%" prefixes).
Attached to this pull request: three programs used in testing: 
[finh-sec-test-1.bas.txt](https://github.com/commanderx16/x16-rom/files/7150064/finh-sec-test-1.bas.txt) …
=> [BASIC] restore C flag in finh to fix null handling in GET/READ/INPUT

kernal/drivers/x16/screen.s
Switching to graphics mode, then back to text mode, is leaving garbage on the screen.  Example:
`SCREEN128:SCREEN0
`
Seen with current ROM & emulator code; also in the web based emulator.
The problem seems to be:
`stz VERA_L0_CONFIG	; Disable layer 0
`
According to VERA Programmer's Reference Guide, zeroing L0_CONFIG won't disable layer 0.  Instead clearing the $10 bit of DC_VIDEO does it.  This corresponds to what's done in FB_init (in kernal/drivers/x16/framebuffer.s) to enable layer 0.
Of course, it's possible real VERA is different; I wouldn't know.
Fixes #165
=> [KERNAL] correctly disable graphics layer when returning to text mode

basic/x16additions.s
In VPEEK() and VPOKE, saving the bank selection on the stack, and not writing it to VERA_ADDR_H until *after* the address (and, for VPOKE, value) is computed.  Without that, VPEEK() within VPOKE or another VPEEK() between two banks won't work right.
The most likely use case (the one reported in #167) is `VPOKE B1, A1, F(VPEEK(B2, A2))` but `VPOKE B1, F(VPEEK(B2, A)), V` and `VPEEK(B1, F(VPEEK(B2, A)))` would also have issues.  (Writing `F(X)` as shorthand for "some expression involving `X`".)
This fixes #167 .
On the downside, it adds 1.9 microseconds to VPEEK() and VPOKE; but that's only 0.4%.
Attached: two test programs:
[issue-167-3.bas.txt](https://github.com/commanderx16/x16-rom/files/7270840/issue-167-3.bas.txt)
[issue-167-4.bas.txt](https://github.com/commanderx16/x16-rom/files/7270 …
=> [BASIC] save bank setting in VPOKE and VPEEK so it won't be lost;

kernal/drivers/x16/memory.s
This pull request fixes issue #234
The FETVEC function did support only ROM banks 0-7, but is here changed to support ROM banks 0-31. According to the PRG, the X16 Edit will have 512 kB of ROM => 512 kB / 16 kB = 32 banks
=> Fix: Changed Kernal FETVEC function to support 32 ROM banks

codex/Makefile, codex/src/cx-dc.s, codex/src/cx.s, codex/src/decoder.s, codex/src/edit.s, codex/src/encode.s, codex/src/fio.s, codex/src/meta.s, codex/src/meta_i.s, codex/src/screen.s, codex/test/utest.s
This fixes issue #276. Previous pull request fixed many issues in CODEX, but plugins were disabled. This PR fixes the regression. Also includes corrections for many TODOs embedded in CODEX, resulting in some byte savings. (needed for future work).
=> Fixes (and optimizations) for CODEX regression on PR 269.

basic/code17.s, basic/code26.s, basic/init.s, basic/token2.s, basic/tokens.s, basic/x16additions.s, cfg/basic-x16.cfgtpl, cfg/x16.cfginc
Implementation of a new BANK statement in BASIC.
The bank set by BANK is used by SYS, POKE and PEEK if the target address is >= $a000
Example (starts GEOS by calling $C000 in ROM bank 3):
```
BANK 3
SYS $C000
```
=> Basic bank statement

basic/x16additions.s, geos/kernal/mouse/mouse2.s
I have a partial fix of GEOS issues:
- After launching GEOS, the mouse don't work. Sometimes it will not be moving at all. Sometimes it moves within a very confined space at screen top left corner. It seems this is simply due to mouse screen resolution params not set correctly on GEOS init.
- I'm not sure my other commit is necessary, but I think it might be. GEOS is launched by the BASIC statement GEOS, that is code running in ROM bank 4. That code will switch to GEOS ROM bank 3 and call the entry point at $c000. As far as I can tell, GEOS has its own IRQ handler which is called by the IRQ vector ($fffe-ffff, IIRC). I guess bad things could happen if the IRQ handler is called before GEOS is setup. Currently there's a small window for that to happen, between the entry point at $c000 and …
=> Fixing GEOS issues

kernal/cbm/editor.s
I was messing around with box16's added tools, and while looking at the CPU Visualizer, I realized that when you idle at the BASIC prompt, the system spends a lot of time in a busy loop. The emulator can handle the `WAI` instruction (commanderx16/x16-emulator#287), so I figured I'd try to update the ROM to use it. I'm not very familiar with the ROM project, so there might have been a better way to implement this, but I did test it and it did work for me. cc65 lacks a `WAI` mnemonic for the 65C02 (even though it has it for the 65816), so I had to use a `.byte` directive to add it.
=> Add WAI to text input busy loop

kernal/drivers/x16/screen.s
The `screen_get_color` and `screen_set_color` routines didn't take into account screen modes where the text wraps at less than 80 columns.  I added a comparison and a subtraction to each routine, similar to what is already happening in the `screen_get_char` and `screen_set_char` routines.
=> [SCREEN] Fix #353 Color change when deleting across line boundary

math/code18.s, math/code19.s, math/fadd.s, math/fmult.s, math/fsqr.s, math/jumptab.s
fixes issue #352 in which some uses of SQR() in BASIC hung or overflowed
Passes the "fp/" tests -- giving the same result as before. On the two one-liners given in #352, it doesn't overflow/hang but gives the same results as Commodore 64.
=> [MATH] adjust calls and comments to functions renamed "bfaddt" etc

basic/graph.s, basic/token2.s
with a new error message for it, "?NOT GRAPHICS MODE". This changes the commands PSET, LINE, RECT, FRAME, and CHAR.
The old behavior was:
PSET, LINE, RECT, and FRAME would crash to monitor, if graphics mode had never been entered. (CHAR didn't.) If graphics mode had been entered and exited, they appeared to do nothing.
This fix does impose a performance penalty, calling "screen_mode" with each operation. The attached test program [gfx-speed-2.bas.txt](https://github.com/commanderx16/x16-rom/files/9885186/gfx-speed-2.bas.txt)
showed a performance penalty of 40.5 microseconds per command -- 6.2% of the time for PSET (the fastest of the commands).
Some alternative ways of finding out the screen mode didn't turn out well.
=> [BASIC] fail graphics commands in non graphics mode (#342)

.github/workflows/build.yml
Get Github Actions to spin up a Ubuntu machine, clone, compile and install the latest cc65 toolchain from the git on it, make the ROM image, upload as an artefact. Very simplistic. See [here](https://github.com/maxgerhardt/x16-rom/actions).
The build time of ~1.5 minutes can be shortened if cc65 is installed from the package repos instead of bleeding edge, but I wanted to be sure the latest is used.
Correctly boots to the BASIC prompt when paired with the lates x16-emulator build.
=> Build ROM in CI

kernal/cbm/editor.s
When you move the cursor the first time after boot using any of the cursor keys, most often a ghost cursor char (inverted space) is left behind at the cursor startup position. After the initial move, the cursor behaves normally.
The problem seems to be in the editor init function (label "cint"), more precisely that the variable blnon is set to 2. Before commit 7574681 the variable was initialized to 0. If you change the code so that the variable is set to 0 on boot as it was earlier, the problem goes away as far as I can tell.
This would solve issue #372
=> Ghost cursor char left behind when moving the cursor first time after boot
